# Generated by Django 3.2.9 on 2021-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPages', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='albums', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('tel', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('rate', models.IntegerField(default=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Универсальный', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pagesCount', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='in_progress', max_length=20)),
                ('albumLayout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.albumlayout')),
                ('albumPattern', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.albumpattern')),
                ('package', models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='album.package')),
            ],
        ),
        migrations.AddField(
            model_name='albumpattern',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.theme'),
        ),
        migrations.AddField(
            model_name='albumlayout',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.size'),
        ),
        migrations.AddField(
            model_name='albumlayout',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.albumtype'),
        ),
    ]
