# Generated by Django 3.2.9 on 2021-11-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
