# Generated by Django 3.2.9 on 2021-11-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20211112_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.AlterModelOptions(
            name='albumlayout',
            options={'verbose_name': 'Макет альбомов', 'verbose_name_plural': 'Макеты альбомов'},
        ),
        migrations.AlterModelOptions(
            name='albumpattern',
            options={'verbose_name': 'Шаблон альбома', 'verbose_name_plural': 'Шаблоны альбомов'},
        ),
        migrations.AlterModelOptions(
            name='albumtype',
            options={'verbose_name': 'Тип альбомов', 'verbose_name_plural': 'Типы альбомов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelTable(
            name='albumlayout',
            table='albumLayout',
        ),
        migrations.AlterModelTable(
            name='albumpattern',
            table='albumPattern',
        ),
        migrations.AlterModelTable(
            name='albumtype',
            table='albumType',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='size',
            table='size',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='theme',
        ),
    ]
