# Generated by Django 3.2.9 on 2021-11-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20211112_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=500, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=45, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='albumlayout',
            name='minPages',
            field=models.IntegerField(default=10, verbose_name='Минимальное кол-во страниц'),
        ),
        migrations.AlterField(
            model_name='albumlayout',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='albumlayout',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.albumtype', verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='albumpattern',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.theme', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='albumpattern',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='albumLayout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.albumlayout', verbose_name='Макет альбома'),
        ),
        migrations.AlterField(
            model_name='order',
            name='albumPattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='album.albumpattern', verbose_name='Шаблон альбома'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pagesCount',
            field=models.IntegerField(default=10, verbose_name='Кол-во страниц'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tel',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
