# Generated by Django 3.2.9 on 2021-11-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20211112_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tel',
        ),
    ]
